version: '3.8'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - infra/.env

  backend:
    image: kuchishkinmax/foodgram_back:latest
    restart: always
    volumes:
      - data_value:/app/data/
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - infra/.env

  frontend:
    image: kuchishkinmax/foodgram_front:latest
    volumes:
      - result_build:/app/result_build/build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/static/
      - media_value:/media/
      - result_build:/usr/share/nginx/html/
      - result_build:/usr/share/nginx/html/api/docs/
    depends_on:
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value:
  data_value:
  result_build: